const words = [
  { word: "abacaxi", clue: "Fruta tropical" },
    { word: "elefante", clue: "Animal de grande porte com tromba longa" },
    { word: "computador", clue: "Dispositivo eletrônico" },
    { word: "girafa", clue: "Animal alto, com pescoço longo" },
    { word: "chocolate", clue: "Doce feito de cacau" },
    { word: "piano", clue: "Instrumento musical com teclas" },
    { word: "tigre", clue: "Felino selvagem" },
    { word: "esmeralda", clue: "Tipo de pedra preciosa" },
    { word: "navio", clue: "Embarcação no mar" },
    { word: "telefone", clue: "Dispositivo de comunicação" },
    { word: "floresta", clue: "Área com muitas árvores" },
    { word: "quadrado", clue: "Figura geométrica de quatro lados" },
    { word: "foguete", clue: "Veículo espacial" },
    { word: "sorvete", clue: "Doce gelado" },
    { word: "bicicleta", clue: "Veículo de duas rodas" },
    { word: "avião", clue: "Meio de transporte aéreo" },
    { word: "macaco", clue: "Primate arbóreo" },
    { word: "raios", clue: "Descargas elétricas na atmosfera" },
    { word: "montanha", clue: "Elevação natural da terra" },
    { word: "vela", clue: "Objeto para iluminação" },

    { word: "cachorro", clue: "Animal de estimação popular" },
    { word: "guitarra", clue: "Instrumento musical de cordas" },
    { word: "caneta", clue: "Objeto para escrever" },
    { word: "janela", clue: "Abertura em paredes para luz e ar" },
    { word: "livro", clue: "Objeto com páginas e conteúdo escrito" },
    { word: "escola", clue: "Lugar de aprendizado" },
    { word: "camisa", clue: "Peça de roupa" },
    { word: "sapato", clue: "Calçado para os pés" },
    { word: "lápis", clue: "Objeto para desenhar ou escrever" },
    { word: "bola", clue: "Objeto usado em esportes" },
    { word: "pássaro", clue: "Animal que voa" },
    { word: "carroça", clue: "Veículo puxado por animais" },
    { word: "rio", clue: "Curso de água natural" },
    { word: "sol", clue: "Estrela do nosso sistema solar" },
    { word: "lua", clue: "Satélite natural da Terra" },
    { word: "estrela", clue: "Corpo celeste brilhante" },
    { word: "prédio", clue: "Construção alta" },
    { word: "mesa", clue: "Móvel para apoiar objetos" },
    { word: "cadeira", clue: "Móvel para sentar" },
    { word: "chave", clue: "Objeto para abrir fechaduras" },

    { word: "telefone", clue: "Dispositivo de comunicação" },
    { word: "relógio", clue: "Objeto para medir o tempo" },
    { word: "porta", clue: "Entrada de um cômodo" },
    { word: "fita", clue: "Material longo e fino" },
    { word: "bola", clue: "Usada em jogos e esportes" },
    { word: "copo", clue: "Recipiente para líquidos" },
    { word: "caneca", clue: "Copo com alça" },
    { word: "cadeado", clue: "Tranca objetos" },
    { word: "guarda-chuva", clue: "Protege da chuva" },
    { word: "chinelos", clue: "Calçado leve" },
    { word: "colar", clue: "Acessório usado no pescoço" },
    { word: "anel", clue: "Acessório para dedo" },
    { word: "óculos", clue: "Usado para ver melhor" },
    { word: "boné", clue: "Protege do sol" },
    { word: "mochila", clue: "Usada para carregar objetos" },
    { word: "bolsa", clue: "Usada para carregar pertences" },
    { word: "notebook", clue: "Computador portátil" },
    { word: "tablet", clue: "Dispositivo touchscreen" },
    { word: "teclado", clue: "Usado para digitar" },
    { word: "mouse", clue: "Controla o cursor do computador" },

    { word: "mar", clue: "Grande massa de água salgada" },
    { word: "praia", clue: "Local de areia perto do mar" },
    { word: "ilha", clue: "Terra cercada de água" },
    { word: "deserto", clue: "Área com pouca água" },
    { word: "neve", clue: "Água congelada que cai do céu" },
    { word: "chuva", clue: "Água que cai do céu" },
    { word: "vento", clue: "Ar em movimento" },
    { word: "nuvem", clue: "Formação de vapor de água no céu" },
    { word: "tempestade", clue: "Condição climática severa" },
    { word: "trovão", clue: "Som da tempestade" },
    { word: "relâmpago", clue: "Luz da tempestade" },
    { word: "flor", clue: "Parte colorida das plantas" },
    { word: "árvore", clue: "Planta alta com tronco" },
    { word: "fruta", clue: "Alimento natural das plantas" },
    { word: "verdura", clue: "Alimento feito de plantas" },
    { word: "legume", clue: "Comida vegetal" },
    { word: "carne", clue: "Alimento de origem animal" },
    { word: "peixe", clue: "Animal aquático comestível" },
    { word: "ave", clue: "Animal que voa" },

    { word: "gelo", clue: "Água congelada" },
    { word: "fogo", clue: "Chama e calor" },
    { word: "terra", clue: "Solo e planeta" },
    { word: "ar", clue: "Gás invisível que respiramos" },
    { word: "lago", clue: "Corpo de água cercado por terra" },
    { word: "cachoeira", clue: "Água caindo de altura" },
    { word: "ponte", clue: "Conecta duas áreas" },
    { word: "estrada", clue: "Via de transporte" },
    { word: "trem", clue: "Transporte sobre trilhos" },
    { word: "ônibus", clue: "Transporte coletivo" },
    { word: "metrô", clue: "Trem urbano subterrâneo" },
    { word: "esquilo", clue: "Animal que adora nozes" },
    { word: "urso", clue: "Grande mamífero peludo" },
    { word: "lobo", clue: "Felino ou canino selvagem" },
    { word: "cavalo", clue: "Animal usado para montar" },
    { word: "ovelha", clue: "Animal que fornece lã" },
    { word: "vaca", clue: "Animal que fornece leite" },
    { word: "galinha", clue: "Ave doméstica" },

    { word: "melancia", clue: "Fruta grande e suculenta" },
    { word: "morango", clue: "Fruta vermelha pequena" },
    { word: "abacate", clue: "Fruta verde cremosa" },
    { word: "laranja", clue: "Fruta cítrica" },
    { word: "limão", clue: "Fruta ácida" },
    { word: "pera", clue: "Fruta doce e suculenta" },
    { word: "maçã", clue: "Fruta famosa e redonda" },
    { word: "uva", clue: "Fruta pequena usada em vinhos" },
    { word: "cereja", clue: "Fruta pequena e vermelha" },
    { word: "amora", clue: "Fruta roxa escura" },
    { word: "figo", clue: "Fruta doce" },
    { word: "kiwi", clue: "Fruta verde com sementes" },
    { word: "manga", clue: "Fruta tropical doce" },
    { word: "papaya", clue: "Fruta grande tropical" }
];

export default function getWord() {
  const index = Math.floor(Math.random() * words.length);
  return words[index];
}